spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST_LIVE}:5432/${POSTGRES_DB_LIVE}
    username: ${POSTGRES_USER_LIVE}
    password: ${POSTGRES_PASSWORD_LIVE}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: ${SHOW_SQL}
  cache:
    redis:
      cache-null-values: true
      time-to-live: 40000
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
