spring:
  datasource:
    communication:
      sql:
        url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_COMMUNICATION_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
    show-sql: ${SHOW_SQL}
  cache:
    redis:
      cache-null-values: true
      time-to-live: 40000
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  port: ${COMMUNICATION_SERVICE_PORT}

mail:
  server:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    ssl: ${MAIL_SSL}