spring:
  datasource:
    account:
      sql:
        url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_ACCOUNT_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: ${SHOW_SQL}
  cache:
    redis:
      cache-null-values: true
      time-to-live: 40000
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  flyway:
    enabled: true
    locations: classpath:db/migration/account
    table: account_flyway_schema_history

server:
  port: ${ACCOUNT_SERVICE_PORT}