CREATE TABLE mail
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mail_header    VARCHAR(255),
    mail_to        VARCHAR(255)                            NOT NULL,
    mail_content   OID,
    sent           BOOLEAN                                 NOT NULL,
    failure_reason OID,
    created_on     TIMESTAMP WITHOUT TIME ZONE,
    last_sent      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_mail PRIMARY KEY (id)
);

CREATE TABLE mail_attachments
(
    mail_id         BIGINT       NOT NULL,
    attachments     VARCHAR(255),
    attachments_key VARCHAR(255) NOT NULL,
    CONSTRAINT pk_mail_attachments PRIMARY KEY (mail_id, attachments_key)
);

CREATE TABLE mail_copy
(
    mail_id BIGINT NOT NULL,
    copy    VARCHAR(255)
);

CREATE TABLE notification
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(255)                            NOT NULL,
    content         OID,
    notification_to VARCHAR(255)                            NOT NULL,
    sent            BOOLEAN                                 NOT NULL,
    failure_reason  OID,
    created_on      TIMESTAMP WITHOUT TIME ZONE,
    last_sent       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_notification PRIMARY KEY (id)
);

CREATE TABLE sms
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sms_to         VARCHAR(255)                            NOT NULL,
    sms_content    OID,
    sent           BOOLEAN                                 NOT NULL,
    failure_reason OID,
    created_on     TIMESTAMP WITHOUT TIME ZONE,
    last_sent      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_sms PRIMARY KEY (id)
);

ALTER TABLE mail_attachments
    ADD CONSTRAINT fk_mail_attachments_on_mail FOREIGN KEY (mail_id) REFERENCES mail (id);

ALTER TABLE mail_copy
    ADD CONSTRAINT fk_mail_copy_on_mail FOREIGN KEY (mail_id) REFERENCES mail (id);